### ISSUE TITLE
Support for HTTP connection?

### ISSUE THREAD

**Issue by PlamenHristov** [PolymathNetwork/polymesh-sdk#676]
Hey team,

Is it possible to use the SDK with an HTTP provider and, if yes, how?
If not, do you plan on supporting it at any point?

**Comment by VictorVicente** [comment]
Hey @PlamenHristov,

Sadly it is not possible. It's a limitation from the library we're using to interact with the chain, Polkadot.js. 
SDK/Polkadot.js needs a websocket connection (rather than https) as it relies on bi-directional communication.

From their documentation (https://polkadot.js.org/docs/api/start/create):

> At this time the only provider type that is fully supported by the API is the WebSocket version. Polkadot/Substrate really comes alive with possibilities once you have access to bi-directional RPCs such as what WebSockets provide. (It is technically possible to have some limited capability via bare-HTTP, but at this point WebSockets is the only fully-operational and supported version - always remember that it is just "upgraded HTTP".)

If they in the future add support to HTTP connections, we'll be happy to integrate them too.

**Comment by PlamenHristov** [comment]
I see. Thanks Victor!
